import type { ErrorCode } from '@open-boox/shared';

export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  LOAN_LIMIT_EXCEEDED: 409,
  OUT_OF_STOCK: 409,
  NO_COPY_AVAILABLE: 409,
  SUBSCRIPTION_INACTIVE: 409,
  SUBSCRIPTION_ALREADY_EXISTS: 409,
  ORDER_NOT_CANCELLABLE: 409,
  INVALID_SHIPMENT_TRANSITION: 409,
  LOAN_NOT_RETURNABLE: 409,
  DUPLICATE: 409,
  IN_USE: 409,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_ERROR: 500,
};
